"""Measure how selective the CIA misuse signal is — the number that shaped its design.

A dynamic signal is only useful if it fires on a minority of calls. This counts,
over every scored (tool, asset) cell in the v5 matrices, how often the CIA signal
says *on-axis* — the call violates the objective that asset's policy register
protects first.

The result is why the signal QUALIFIES rather than escalates: at a ~50 % firing
rate, using it to add a band would push half the matrix up and swamp the
distribution — the same inflation failure as the v1 CIA arm. Used to withhold an
escalation instead, a high firing rate is harmless: it just means the qualifier
rarely blocks anything, and the precision it buys comes from the other half.

Run:  uv run python scripts/cia_signal_selectivity.py
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path
from types import SimpleNamespace

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from mcp_security.dynamic.cia import ON_AXIS_BAND, leading_facets, score_cia  # noqa: E402

V5_DIR = REPO_ROOT / "reports" / "experiments" / "v5" / "five_level_v2_policy_v5"
DEFAULT_OUT = REPO_ROOT / "reports" / "experiments" / "v6" / "cia_misuse_signal"
STEMS = ("calendar_real", "github_real", "slack_real")


def measure(stem: str, v5_dir: Path) -> dict:
    """Firing rate and the per-cell verdicts for one server."""
    table = json.loads((v5_dir / f"{stem}.json").read_text(encoding="utf-8"))
    register = list(
        csv.DictReader(
            (v5_dir / "inputs" / f"{stem}.register.csv").read_text(encoding="utf-8").splitlines()
        )
    )
    axes = {row["asset"]: leading_facets(row["cia"]) for row in register}
    tool_ops = {
        tool: (spec or {}).get("atomic_ops") or []
        for tool, spec in table.get("tool_atomic_ops", {}).items()
    }

    rows: list[dict] = []
    for asset in table["asset_ids"]:
        for tool in table["tool_impact"]:
            if table["blast_radius"].get(f"{tool}|{asset}") is None:
                continue  # N/A pair: the tool does not act on this asset
            band, reason = score_cia(SimpleNamespace(tool=tool, asset=asset), axes, tool_ops)
            rows.append(
                {
                    "asset": asset,
                    "tool": tool,
                    "protects": "/".join(sorted(axes.get(asset) or [])) or "(unstated)",
                    "violates": "+".join(tool_ops.get(tool, [])) or "(unclassified)",
                    "cia_band": band,
                    "on_axis": band == ON_AXIS_BAND,
                    "reason": reason,
                    "static_band": table["bands"][asset][tool],
                }
            )
    fired = sum(1 for row in rows if row["on_axis"])
    # An asset whose register states no loss priority can never fire — worth
    # surfacing, since it is a gap in the policy rather than a property of the rule.
    silent_assets = sorted({a for a, facets in axes.items() if not facets})
    return {
        "stem": stem,
        "server": table["server"],
        "scored_cells": len(rows),
        "on_axis": fired,
        "off_axis": len(rows) - fired,
        "firing_rate": round(fired / len(rows), 3) if rows else None,
        "assets_with_no_stated_priority": silent_assets,
        "_rows": rows,
    }


def render_markdown(results: list[dict]) -> str:
    head = "| server | scored cells | on-axis | off-axis | firing rate |"
    rule = "|---|--:|--:|--:|--:|"
    body = [
        f"| {r['stem']} | {r['scored_cells']} | {r['on_axis']} | {r['off_axis']} "
        f"| **{r['firing_rate'] * 100:.1f} %** |"
        for r in results
    ]
    total_cells = sum(r["scored_cells"] for r in results)
    total_fired = sum(r["on_axis"] for r in results)
    out = [
        "# CIA misuse signal — selectivity",
        "",
        "How often the signal says *on-axis*: the call violates the objective the",
        "asset's policy register protects first. Measured over every scored cell of the",
        "v5 matrices. Generated by `scripts/cia_signal_selectivity.py` — do not hand-edit.",
        "",
        head,
        rule,
        *body,
        f"| **total** | **{total_cells}** | **{total_fired}** | "
        f"**{total_cells - total_fired}** | **{100 * total_fired / total_cells:.1f} %** |",
        "",
        "## Why this number decided the design",
        "",
        "At roughly one cell in two, using CIA to **add** a band would raise half the",
        "matrix — the same inflation the v1 CIA arm produced (`impact = base + C + I + A`",
        "moved calendar's `high` band from 8 to 25 cells) and the same failure the",
        "static-matrix work in [`../DESIGN.md`](../DESIGN.md) was trying to avoid.",
        "",
        "Inverting it removes the problem. As a **qualifier** the signal can only",
        "withhold a baseline or sequence escalation, never create one, so:",
        "",
        "- the static floor always stands — nothing is under-scored;",
        "- a high firing rate is harmless — it means the qualifier rarely blocks;",
        "- the value comes from the off-axis half, where a behavioural deviation is",
        "  held back because it attacks an objective the asset does not protect.",
        "",
        "## Assets that can never fire",
        "",
        "An asset whose register states no loss priority abstains permanently. That is a",
        "gap in the policy text, not a property of the rule:",
        "",
    ]
    for r in results:
        silent = r["assets_with_no_stated_priority"]
        out.append(f"- **{r['stem']}** — {', '.join(f'`{a}`' for a in silent) if silent else 'none'}")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--v5-dir", type=Path, default=V5_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    results = [measure(stem, args.v5_dir) for stem in STEMS]

    (args.out_dir / "SELECTIVITY.md").write_text(render_markdown(results), encoding="utf-8")
    (args.out_dir / "selectivity.json").write_text(
        json.dumps(
            [{k: v for k, v in r.items() if not k.startswith("_")} for r in results], indent=2
        ),
        encoding="utf-8",
    )
    for r in results:
        buffer = io.StringIO()
        writer = csv.DictWriter(buffer, fieldnames=list(r["_rows"][0]))
        writer.writeheader()
        writer.writerows(r["_rows"])
        (args.out_dir / f"{r['stem']}_signal.csv").write_text(buffer.getvalue(), encoding="utf-8")
        print(
            f"[ok] {r['stem']}: on-axis {r['on_axis']}/{r['scored_cells']} "
            f"({r['firing_rate'] * 100:.1f}%)"
        )
    print(f"\nwrote SELECTIVITY.md, selectivity.json and per-server CSVs to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
