"""Render the policy-derived asset sensitivities as one markdown report.

Reads every artifact in ``reports/experiments/staticscanner/``
(the scan that derives sensitivity from ``docs/mcp-tools/server-policies.md``)
and writes one section per MCP: each enumerated asset, the 1-5 the scanner
derived, and — when the server's policy section carries an asset register — the
register's Description and Tools cells for that asset.

Only this scanner's numbers appear. No ground truth, no baseline: use
``scripts/compare_policy_sensitivity.py`` for the three-way comparison.

Run:  python scripts/report_policy_sensitivity.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from mcp_security.static_scoring.server_profiles import (  # noqa: E402
    ProfileNotFoundError,
    profile_for,
)

from scripts.compare_policy_sensitivity import _STEM_TO_SERVER  # noqa: E402

SCAN_DIR = REPO_ROOT / "reports" / "experiments" / "staticscanner"
POLICY_DOC = REPO_ROOT / "docs" / "mcp-tools" / "server-policies.md"
DEFAULT_OUT = SCAN_DIR / "asset-sensitivity.md"

# Register table header: "| Asset | Description | Tools | CIA |".
_REGISTER_HEADER_RE = re.compile(r"^\|\s*Asset\s*\|\s*Description\s*\|", re.IGNORECASE)


def parse_register(text: str) -> dict[str, dict[str, str]]:
    """Parse a policy section's asset register into ``{asset: {col: cell}}``.

    Returns an empty dict when the section carries no register (a P0 policy),
    since the report degrades to sensitivity-only rather than failing.
    """
    rows: dict[str, dict[str, str]] = {}
    columns: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if _REGISTER_HEADER_RE.match(stripped):
            columns = [c.strip().lower() for c in stripped.strip("|").split("|")]
            continue
        if not columns:
            continue
        if not stripped.startswith("|"):
            columns = []
            continue
        if re.match(r"^\|[\s:|-]+\|?\s*$", stripped):
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if len(cells) < len(columns):
            continue
        by_col = dict(zip(columns, cells))
        asset = by_col.get("asset", "").strip().strip("`").strip()
        if asset:
            rows[asset] = by_col
    return rows


def render_server(stem: str, table: dict, register: dict[str, dict[str, str]]) -> list[str]:
    """Markdown for one MCP: a sensitivity row per enumerated asset."""
    sens: dict[str, int] = table.get("asset_sensitivity") or {}
    out = [
        f"## {stem}",
        "",
        f"`{table.get('server')}` · {table.get('server_kind')} · "
        f"{len(table.get('tool_impact', {}))} tools · {len(sens)} assets · "
        f"peak sensitivity **{max(sens.values()) if sens else '—'}**",
        "",
    ]
    if register:
        out += ["| Asset | Sens. | Description | Tools |", "|---|---|---|---|"]
    else:
        out += ["| Asset | Sens. |", "|---|---|"]
    for asset, value in sorted(sens.items(), key=lambda kv: (-kv[1], kv[0])):
        row = register.get(asset, {})
        if register:
            out.append(
                f"| `{asset}` | {value} | {row.get('description', '—')} | "
                f"{row.get('tools', '—')} |"
            )
        else:
            out.append(f"| `{asset}` | {value} |")
    counts = {v: sum(1 for s in sens.values() if s == v) for v in sorted(set(sens.values()))}
    out += ["", "Distribution: " + " · ".join(f"**{v}** × {n}" for v, n in counts.items()), ""]
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scan-dir", type=Path, default=SCAN_DIR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    artifacts = sorted(p for p in args.scan_dir.glob("*.json"))
    if not artifacts:
        print(f"[FAIL] no scan artifacts in {args.scan_dir}")
        return 1

    lines = [
        "# Asset Sensitivity — derived from the org policies",
        "",
        "Per-asset sensitivity (1–5) that the scanner **derived on its own** from each",
        "organization's policy in [`server-policies.md`](../../../docs/mcp-tools/server-policies.md).",  # noqa: E501
        "The policy documents contain no sensitivity numbers: the scanner enumerates the",
        "assets, classifies each against the org's classification table and recognition",
        "rules, and maps the class's adverse-impact language onto the 1–5 rubric.",
        "",
        "Generated by `scripts/report_policy_sensitivity.py` from",
        f"`{args.scan_dir.relative_to(REPO_ROOT)}`. Scoring mode `five_level_v2_na`",
        "with the policy document as org description. Description and Tools cells come",
        "from each policy section's asset register (blank where the section is still",
        "prose-only). No ground truth or baseline appears here — see",
        "`scripts/compare_policy_sensitivity.py` for that.",
        "",
    ]
    for path in artifacts:
        stem = path.stem
        table = json.loads(path.read_text(encoding="utf-8"))
        if not table.get("asset_sensitivity"):
            print(f"[skip] {stem}: artifact has no asset_sensitivity")
            continue
        try:
            section = profile_for(_STEM_TO_SERVER.get(stem, stem), doc=POLICY_DOC).text
            register = parse_register(section)
        except ProfileNotFoundError:
            register = {}
        lines += render_server(stem, table, register)
        print(f"[ok] {stem}: {len(table['asset_sensitivity'])} assets"
              f"{' (with register)' if register else ''}")

    args.out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"-> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
